### ISSUE TITLE
Cambio de API para info de plazos fijos

### ISSUE THREAD

**Issue by ferminrp** [ferminrp/compara-tasas#20]
Tenemos que migrar la fuente de informacion de los plazos fijos a Argentina Datos.

[https://argentinadatos.com/docs/operations/get-finanzas-tasas-plazo-fijo.html](https://argentinadatos.com/docs/operations/get-finanzas-tasas-plazo-fijo.html)

Lo ideal seria tener un mapeo de Nombre en el api a nombre que queremos mostrar. Para por ejemplo en vez de mostrar "BANCO DE GALICIA Y BUENOS AIRES S.A.U." mostrar "Galicia".

Tambien creo que haria una whitelist para mostrar solo los mas relevantes.

**Comment by enzonotario** [comment]
Quizás podamos sumar ese Mapeo de Nombres a ArgentinaDatos, ya que también será útil para quienes consuman los datos de los FCIs. Algo como `/v1/finanzas/fci/nombres`.

¿cómo crees que debería ser la Respuesta? estaba pensando en algo como:

```
{
    "nombre": "string",
    "fondos": [
      "string"
    ]
}
```

Ejemplo:

```
{
    "nombre": "FCI - Nombre Comercial",
    "fondos": [
      "Fondo Común de Inversión - Clase A",
      "Fondo Común de Inversión - Clase B",
      "..."
    ]
}
```

**Comment by FacuMasino** [comment]
La whitelist podría ser algo así?

```json
[
    {
        "entidad": "BANCO DE LA NACION ARGENTINA",
        "nombre": "Banco Nacion"
    },
    {
        "entidad": "BANCO SANTANDER ARGENTINA S.A.",
        "nombre": "Santander"
    },
    {
        "entidad": "BANCO DE GALICIA Y BUENOS AIRES S.A.U.",
        "nombre": "Galicia"
    },
    {
        "entidad": "BANCO DE LA PROVINCIA DE BUENOS AIRES",
        "nombre": "Banco Provincia"
    },
    {
        "entidad": "BANCO BBVA ARGENTINA S.A.",
        "nombre": "BBVA"
    },
    {
        "entidad": "BANCO MACRO S.A.",
        "nombre": "Macro"
    },
    {
        "entidad": "HSBC BANK ARGENTINA S.A.",
        "nombre": "HSBC"
    },
    {
        "entidad": "BANCO CREDICOOP COOPERATIVO LIMITADO",
        "nombre": "Credicoop"
    },
    {
        "entidad": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (ARGENTINA) S.A.U.",
        "nombre": "ICBC"
    },
    {
        "entidad": "BANCO COMAFI SOCIEDAD ANONIMA",
        "nombre": "Comafi"
    },
    {
        "entidad": "BANCO HIPOTECARIO S.A.",
        "nombre": "Hipotecario"
    }
]
```

**Comment by AdrielIg** [comment]
Habria que agregarle TEA a la api si lo vamos a querer mostrar para plazo fijo tambien
