### ISSUE TITLE
Error en la tasa de BV PPay y NX 

### ISSUE THREAD

**Issue by arwenekaitza** [ferminrp/compara-tasas#254]
Gente, estan actualizadas en comparatasasar las tasas de interes que paga cada una? 
Gracias!!

![PersonalPay](https://github.com/ferminrp/compara-tasas/assets/168915217/fcfe999e-6777-4cbe-934e-b1ab59f52611)
![Naranja NX](https://github.com/ferminrp/compara-tasas/assets/168915217/963690fd-44ca-4efe-ba40-e592cb9480f6)

**Comment by ferminrp** [comment]
Si, están actualizadas
