### ISSUE TITLE
Actualización de los datos

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [ferminrp/compara-tasas#268]
Cada cuanto tiempo se actualizan los datos de la pagina? Más especificamente, cada cuanto se actualizan las tasas de las Cuentas Remuneradas?

**Comment by ferminrp** [comment]
Depende que dato. Rendimientos en pesos se actualiza una vez por dia.

**Comment by ItsIgnacioPortal** [comment]
muchas gracias
