### ISSUE TITLE
¿Licencia del código?

### ISSUE THREAD

**Issue by riveravaldez** [ferminrp/compara-tasas#281]
Qué tal, buen día, perdón si no es el lugar apropiado para consultar, pero estuve mirando un poco y no encontré dónde está especificada la licencia bajo la cual se desarrolla el código, ¿puede ser?
Saludos y gracias desde ya, muy bueno el trabajo que están haciendo. 😃

**Comment by riveravaldez** [comment]
Qué tal, no entiendo bien por qué está cerrado...
Saludos

**Comment by ferminrp** [comment]
Listo! ahi sume LICENSE en el root

**Comment by riveravaldez** [comment]
¡Perfecto, gracias!
Saludos
