### ISSUE TITLE
Añadir menu lateral derecho desplegable

### ISSUE THREAD

**Issue by AdrielIg** [ferminrp/compara-tasas#48]
En el PR habria que inlcuir:

- Menu hamburguesa
- Apertura y cierre de panel
- Los anchor de Rendimientos y Comisiones

Tambien agregar una feature flag para ocultar el menu hasta tener las otras paginas hechas, la idea es que el usuario no puedo ver el menu, ni abrirlo hasta que no tengamos algunas de las paginas que vamos a mostrar

![image](https://github.com/ferminrp/compara-tasas/assets/75552918/3cc90055-ab98-4f9b-af4d-55c12eb1a1ec)

**Comment by ferminrp** [comment]
Sumo el diseño de @deskfolio que es mas agradable a la vista.
![image](https://github.com/ferminrp/compara-tasas/assets/21282919/eb1c28f2-934d-4db0-942b-0e5795f6c2b0)

**Comment by matigumma** [comment]
[https://github.com/matigumma/compara-tasas/tree/feature/drawer%2348](https://github.com/matigumma/compara-tasas/tree/feature/drawer%2348)
un acercamiento al issue
resta 
- poner activo el menu actual
- crear los sections para cada caso
