### ISSUE TITLE
Añadir página /rendimientos-en-pesos

### ISSUE THREAD

**Issue by ferminrp** [ferminrp/compara-tasas#50]
Una página con todas las opciones de inversion en pesos por casa.

Se puede usar la información en [estos endpoints](https://discordapp.com/channels/1205894470504026112/1205894610140790784/1209269557185749053).

[Mockups](https://discord.com/channels/1205894470504026112/1211788755011248168/1212542760733904926)

**Comment by AdrielIg** [comment]
Nuevo [mockup](https://discord.com/channels/1205894470504026112/1211788755011248168/1212542760733904926)
