### ISSUE TITLE
Título principal encabezado quedó desactualizado y poco relacionado

### ISSUE THREAD

**Issue by deskfolio** [ferminrp/compara-tasas#51]
## Título Actual
En el encabezado actual de la página se puede leer el siguiente título que, habiendo incorporado más contenido/instrumentos, parecería haber quedado desactualizado:

> ¡Elegí el fondo con más rendimientos para vos!

## Sugerencia
Se propone algo más genérico, relacionado con la idea de "invertir":

> ¡Descubrí cuánto podés hacer rendir tu plata!

O similar, pero siempre en relación con el hecho de invertir y no asociado solamente a un instrumento en particular (fondo).

**Comment by ferminrp** [comment]
Me surgio la duda, descubris cuanto o descubris "como" / "en donde" ?
