### ISSUE TITLE
Footer & Sección Aviso Legal

### ISSUE THREAD

**Issue by deskfolio** [ferminrp/compara-tasas#58]
## Problema
En el footer actual no se mencionan aspectos legales sobre la información expuesta en el sitio ni responsabilidades, lo cual podría representar un problema legal.

## Solución

Se sugiere reemplazar el contenido actual del footer, por una breve descripción del sitio (para qué se hizo, quién lo hace) y facilitar al usuario del sitio, un link a una página/sección muy simple que tenga un texto bajo el nombre "Aviso Legal", que pueda explicar el alcance de las responsabilidades de los colaboradores de la página.

## Comentarios

- El texto propuesta está altamente "inspirado" en la sección legal del sitio web [dolarhoy.com](https://dolarhoy.com/) pero ajustado para comparatasas.
- Desde el aspecto legal, es necesario destacar las fuentes/proveedores de las API (ej: "La cotización del dolar es provista por dolarapi.com"), o es sólo una mención/crédito?
- La itálica fue removida del estilo, porque esto no es VENECIA, gracias

## Propuesta

<img width="830" alt="Captura de pantalla 2024-02-21 a la(s) 14 18 10" src="https://github.com/ferminrp/compara-tasas/assets/1668574/5c20d4df-400b-4e51-9c71-023fa9e783fd">

### Contenido sección Footer:

> Comparatasas.com.ar® es un proyecto colaborativo que tiene como fin, reflejar las tasas disponibles en el mercado actual. Para mayor información, visitá la sección [Aviso Legal](url)

### Contenido sección "Aviso Legal":

>Comparatasas.com.ar® es un sitio meramente informativo, y no brinda consejo, recomendación, asesoramiento o invitación de ningún tipo, ni de ninguna clase o naturaleza, para realizar actos y/o operaciones de cualquier tipo, clase o naturaleza. <br/>
Los colaboradores de este sitio se deslindan de toda responsabilidad respecto de la posible falta de precisión y/o veracidad y/o exactitud y/o integridad y/o vigencia de los datos y/o de las fuentes de información de público acceso tenidos en consideración para la elaboración del contenido del sitio. Los colaboradores de este sitio no garantizan la precisión y/o veracidad y/o exactitud y/o integridad y/o vigencia de los datos mostrados en este sitio.<br/>
Los colaboradores de este sitio se deslindan de toda responsabilidad respecto del uso que puedan llegar a dar a la información y/o a los datos incluidos en el contenido de este sitio quienes accedan al mismo.<br/>
Los colaboradores de este sitio no se responsabilizan por los eventuales daños patrimoniales y/o perjuicios que pudieren resultar de decisiones adoptadas sobre la base de los datos mostrados en este sitio, por quienes accedan al mismo. Se recomienda a las visitas hacer su propia investigación y buscar asesoramiento profesional.

**Comment by ferminrp** [comment]
Lo de dolarapi o argentina datos es para darle credito a enzo por el laburo de proveer toda la info que usamos asi como ser transparentes y que no puedan challengear o desacreditar la objetividad de nuestros datos. Todo lo que hacemos es open source y facil mente trazable/comprobable

**Comment by deskfolio** [comment]
@ferminrp Fermín, está perfecto. Yo decía para visualizarlo explícitamente en caso que fuera una cuestión de crédito.
